version: '3'

services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:5.0.7-buster